### ISSUE TITLE
Hi, why the output is defferent with the image in your paper?

### ISSUE THREAD

**Issue by striver13** [hezhangsprinter/DCPDN#17]
I think it maybe related to the protrained model which you offer

**Comment by hezhangsprinter** [comment]
To reproduce the quantative results shown in the paper, please save both generated and target using python demo.py  into the .png format and then test using offline tool such as the psnr and ssim measurment in python or matlab.   In addition, please use netG.train()

**Comment by striver13** [comment]
thanks
