### ISSUE TITLE
What is the exact value of sizePatchGAN?

### ISSUE THREAD

**Issue by frankgwo** [hezhangsprinter/DCPDN#24]
Hi! 
I notice that when you define the `netD` in dehaze22.py,  your annotation at line 150 says `sizePatchGAN=30`. However, in train.py, you firstly set `sizePatchGAN = 30` at line 168 but later at line 258 you set `sizePatchGAN=62`. I cannot get your point of doing these manipulations, and I wonder which is the one that you used in your paper? 
Thank you in advance!

**Comment by hezhangsprinter** [comment]
It depends on your input image size.
