### ISSUE TITLE
Edge loss

### ISSUE THREAD

**Issue by xorangecheng** [hezhangsprinter/DCPDN#29]
Hi, 

Thanks for sharing.  I read your paper, the edge-preserving loss contains l2 loss, two-directional gradient loss, and feature edge loss. 
However, in your code, it seems like you used l1 loss, am I right?

Best

**Comment by hezhangsprinter** [comment]
I use all of them in the code.

**Comment by hezhangsprinter** [comment]
I use l2 in the paper.
