### ISSUE TITLE
About “checkpoint” in the command of training part

### ISSUE THREAD

**Issue by 928203628** [hezhangsprinter/DCPDN#32]
Hi!
The command of the training part provided by the author is: python train.py --dataroot ./facades/train512 --valDataroot ./facades/test512 --exp ./checkpoints_new --netG ./demo_model/netG_epoch_8.pth

However, is there any directory called "checkpoints_new", or is this file should be generated by myself? I mean, by which means could I get the file (or directory) "checkpoints_new"?
Really thanks for any help!

**Comment by hezhangsprinter** [comment]
You can just create a directory called checkpoints_new
