### ISSUE TITLE
About unknown error

### ISSUE THREAD

**Issue by 928203628** [hezhangsprinter/DCPDN#33]
Hi,
Thanks for your time!

I tried the "**training**" part command: _python train.py --dataroot ./facades/train512 --valDataroot ./facades/test512 --exp ./checkpoints_new --netG ./demo_model/netG_epoch_8.pth_
But I got the unknown error, the screenshot of the traceback is shown below:
<img width="1390" alt="WechatIMG516" src="https://user-images.githubusercontent.com/30594753/54116150-0bbd3880-43e6-11e9-9966-5fec557416d8.png">
Please notice the last line of the screenshot: **RuntimeError: Unknown error -1**
What is the reason of this unknown error? Where should I make any change?
I am using pytorch 0.4, and some codes are modified according to the 0.4 version. And I use part of the training set providing on google drive, not all the set, due to the memory of disk.

Really thanks for any help!

**Comment by hezhangsprinter** [comment]
I am not sure exactly since I am not using pytroch0.4. I am using 0.3x for this code.
