### ISSUE TITLE
How do you get your final model for testing?

### ISSUE THREAD

**Issue by ImageWQ** [hezhangsprinter/DCPDN#38]
I hope to get your final model for testing. Because the use of "netG_epoch_8.pth" does not feel very good, it may be my equipment and parameter adjustment problems, but still hope to get your final model for reference. Thank you very much.
My email is 1486466700wq@gmail.com or 1486466700@qq.com.

**Comment by hezhangsprinter** [comment]
if you are not reproducing the images shown in the readme, please reproduce first.

**Comment by hezhangsprinter** [comment]
#22
This may help.
