### ISSUE TITLE
 test results on Epoch_8 are not ideal

### ISSUE THREAD

**Issue by wantbe2020** [hezhangsprinter/DCPDN#41]
Hello, my dehazing results obtained with the netG_epoch_8 test are not ideal, and even obvious problems have arisen. Then I analyzed the atmospheric light value A according to the output, mainly because the predicted A is generally too small, only 0.05. So, the final output graph is too bright, what is the cause of this?

**Comment by hezhangsprinter** [comment]
if you are not reproducing the images shown in the readme, please reproduce first.

**Comment by hezhangsprinter** [comment]
#22
This may help.
