### ISSUE TITLE
train code with my own data

### ISSUE THREAD

**Issue by dalianKJR** [hezhangsprinter/DCPDN#9]
Hello, I am reading your paper and try to run train code with my own data. but I don't know how to create haze image from ground truth, trans map and ato map. can you help me?

**Comment by hezhangsprinter** [comment]
All the syn samples (both training and testing) are strored in Hdf5 file. You can also generate your sample using 'create_train.py' (Please download the NYU-depth @ http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/nyu_depth_v2_labeled.mat)
